import { createFixtureRuntime } from './logo-robo-fixture.js';
import { createRuntimeBridge } from '../webmcp/runtime-bridge.js';
import { createLogoRoboToolHandlers } from '../webmcp/tool-handlers.js';
import { projectWorldPoint, topFaceWorldCorners } from '../perception/projection.js';
let runtime, bridge, handlers;
const $=(s)=>document.querySelector(s), svgNS='http://www.w3.org/2000/svg';
function el(name,attrs={}){const n=document.createElementNS(svgNS,name);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;}
function colour(value){return({white:'#e9eef0',black:'#263137',red:'#e94a59',blue:'#448de8',yellow:'#eabb45',green:'#43b974'})[value]??'#879ba4';}
function cameraSvg(containerId,cameraId,snapshot){
  const host=$(containerId);host.innerHTML='';const camera=handlers.observationService.cameraRig.getCamera(cameraId,runtime.getWorldRevision());const svg=el('svg',{viewBox:`0 0 ${camera.widthPx} ${camera.heightPx}`,'aria-label':cameraId});
  for(let x=0;x<=camera.widthPx;x+=40)svg.append(el('line',{x1:x,y1:0,x2:x,y2:camera.heightPx,class:'camera-grid'}));for(let y=0;y<=camera.heightPx;y+=40)svg.append(el('line',{x1:0,y1:y,x2:camera.widthPx,y2:y,class:'camera-grid'}));
  const boardObj={position:{xMm:-110,yMm:205,zMm:0},bounds:{xMm:330,yMm:190,zMm:5}}; if(cameraId==='canvas_camera'){const p=topFaceWorldCorners(boardObj).map(v=>projectWorldPoint(v,camera)).filter(Boolean).map(p=>`${p.xPx},${p.yPx}`).join(' ');svg.append(el('polygon',{points:p,class:'board'}));}
  const state=runtime.fixture.getState(), objects=cameraId==='tray_camera'?state.bricks:state.targets;
  for(const object of objects){if(object.visible===false)continue;const points=topFaceWorldCorners(object).map(v=>projectWorldPoint(v,camera)).filter(Boolean);if(points.length<3)continue;const poly=el('polygon',{points:points.map(p=>`${p.xPx},${p.yPx}`).join(' '),class:cameraId==='tray_camera'?`brick ${object.state==='snapped'?'filled':''}`:`target ${object.status==='filled'?'filled':''}`,style:`--object-colour:${colour(object.colour)}`,fill:cameraId==='tray_camera'?colour(object.colour):object.status==='filled'?colour(object.colour):'#ffffff0a'});svg.append(poly);const c=points.reduce((a,p)=>[a[0]+p.xPx/points.length,a[1]+p.yPx/points.length],[0,0]);const label=el('text',{x:c[0],y:c[1],class:'small-label','text-anchor':'middle'});label.textContent=object.id;svg.append(label);}
  const active=handlers.observationService.getActiveDetection();
  for(const d of snapshot?.detections??[]){const [x0,y0,x1,y1]=d.bboxPx;const isActive=active?.objectId===d.objectId;svg.append(el('rect',{x:x0,y:y0,width:x1-x0,height:y1-y0,rx:2,class:`det-box${isActive?' active':''}`}));if(isActive){const w=190,h=30,ly=Math.max(4,y0-h-3),lx=Math.min(camera.widthPx-w-3,Math.max(3,x0));svg.append(el('rect',{x:lx,y:ly,width:w,height:h,rx:4,class:'det-label-bg'}));const t=el('text',{x:lx+7,y:ly+12,class:'det-label'});t.textContent=`${d.objectId} · ${d.colour}`;svg.append(t);const p=el('text',{x:lx+7,y:ly+24,class:'det-label'});p.textContent=`XYZ ${Math.round(d.worldXmm)}, ${Math.round(d.worldYmm)}, ${Math.round(d.worldZmm)} mm`;svg.append(p);}}
  if(cameraId==='canvas_camera'){const claimed=state.targets.find(t=>t.claimOwner==='agent'&&t.status!=='filled');if(claimed){const d=(snapshot?.detections??[]).find(x=>x.objectId===claimed.id);if(d){const[x0,y0,x1,y1]=d.bboxPx;svg.append(el('rect',{x:x0-4,y:y0-4,width:x1-x0+8,height:y1-y0+8,rx:3,class:'target-box'}));}}}
  host.append(svg);
}
function renderActivity(){const list=handlers.activity.list(),host=$('#activity');host.className='activity-list';host.innerHTML='';for(const e of list.slice(0,7)){const row=document.createElement('div');row.className=`event ${e.state==='RECOVER'?'recover':''}`;row.innerHTML=`<strong>${e.state}</strong><span>${escapeHtml(e.message)}</span><code>#${String(e.sequence).padStart(2,'0')}</code>`;host.append(row);}$('#phase').textContent=list[0]?.state??'OBSERVE';$('#revision').textContent=`REV ${runtime.getWorldRevision()}`;}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function render(){const tray=handlers.observationService.getSnapshot('tray_camera')??await handlers.observeCamera({cameraId:'tray_camera',limit:50});const canvas=handlers.observationService.getSnapshot('canvas_camera')??await handlers.observeCamera({cameraId:'canvas_camera',type:'target',limit:50});cameraSvg('#trayCamera','tray_camera',tray);cameraSvg('#canvasCamera','canvas_camera',canvas);$('#trayCount').textContent=`${tray.detections.length} visible`;$('#canvasCount').textContent=`${canvas.detections.length} visible`;$('#trayMeta').textContent=`${tray.widthPx} × ${tray.heightPx} · rev ${tray.snapshotRevision}`;$('#canvasMeta').textContent=`${canvas.widthPx} × ${canvas.heightPx} · rev ${canvas.snapshotRevision}`;renderActivity();}
function init(){runtime=createFixtureRuntime();bridge=createRuntimeBridge(runtime);handlers=createLogoRoboToolHandlers({bridge});handlers.activity.subscribe(()=>renderActivity());}
async function selectBrick(){const o=await handlers.observeCamera({cameraId:'tray_camera',colour:'white',type:'brick',limit:20}),b=o.detections[0];await handlers.moveTool({xMm:b.worldXmm,yMm:b.worldYmm,zMm:b.worldZmm+100,speedMmS:500});await render();return b;}
async function claim(){await handlers.claimTarget({targetId:'t_001'});await handlers.observeCamera({cameraId:'canvas_camera',type:'target',limit:20});await render();}
async function place(){const state=await handlers.getBuildState({status:'unfilled',colour:'white',limit:10}),target=state.targets[0];await handlers.claimTarget({targetId:target.id});const o=await handlers.observeCamera({cameraId:'tray_camera',colour:'white',type:'brick',limit:20}),b=o.detections[0];await handlers.moveTool({xMm:b.worldXmm,yMm:b.worldYmm,zMm:b.worldZmm+100,speedMmS:500});await handlers.moveTool({xMm:b.worldXmm,yMm:b.worldYmm,zMm:b.worldZmm,speedMmS:200});await handlers.latch();await handlers.moveTool({xMm:b.worldXmm,yMm:b.worldYmm,zMm:b.worldZmm+140,speedMmS:500});await handlers.moveTool({xMm:target.position.xMm,yMm:target.position.yMm,zMm:target.position.zMm+120,speedMmS:500});await handlers.moveTool({xMm:target.position.xMm,yMm:target.position.yMm,zMm:target.position.zMm,speedMmS:180});await handlers.unlatch();await handlers.getBuildState({limit:20});await handlers.observeCamera({cameraId:'canvas_camera',limit:20});await handlers.observeCamera({cameraId:'tray_camera',limit:20});await render();}
async function recovery(){const o=await handlers.observeCamera({cameraId:'tray_camera',colour:'white',type:'brick'}),b=o.detections[0];runtime.fixture.takeBrick(b.objectId);await handlers.moveTool({xMm:b.worldXmm,yMm:b.worldYmm,zMm:b.worldZmm,speedMmS:200});await handlers.observeCamera({cameraId:'tray_camera',colour:'white',type:'brick'});await render();}
async function scenario(name){init();if(name==='observe'){await handlers.observeCamera({cameraId:'tray_camera',limit:50});}else if(name==='target'){await selectBrick();}else if(name==='canvas'){await claim();}else if(name==='placed'){await place();}else if(name==='recovery'){await recovery();}await render();return {name,worldRevision:runtime.getWorldRevision(),activity:handlers.activity.list(),state:runtime.fixture.getState()};}
for(const b of document.querySelectorAll('[data-scenario]'))b.addEventListener('click',()=>scenario(b.dataset.scenario));
window.__ORACLE3_DEBUG__={scenario,get state(){return runtime?.fixture.getState();},get activity(){return handlers?.activity.list();}};
const requested=new URLSearchParams(location.search).get('scenario')??'observe';scenario(requested).catch(e=>{$('#statusText').textContent='ERROR';console.error(e);});
