import test from 'node:test';import assert from 'node:assert/strict';import{compileImageData,EMPTY_COVERAGE_THRESHOLD}from'../../apps/web/src/logo/compiler.js';import{makePattern}from'../../apps/web/src/logo/patterns.js';import{validateBlueprint}from'../../apps/web/src/logo/blueprint.js';
function blank(w=32,h=32){return{width:w,height:h,data:new Uint8ClampedArray(w*h*4)}}function pixel(img,x,y,rgba){const i=(y*img.width+x)*4;img.data.set(rgba,i)}
test('transparent image is rejected as no candidate',()=>{assert.throws(()=>compileImageData(blank(),{brickBudget:40}),/no_candidate_under_budget/)});
test('deterministic compile gives exact same blueprint',()=>{const image=makePattern('ring',96),a=compileImageData(image,{brickBudget:48,seed:77}).blueprint,b=compileImageData(image,{brickBudget:48,seed:77}).blueprint;assert.deepEqual(a,b);assert.equal(a.blueprintId,b.blueprintId)});
test('grid is even, within budget, stable IDs, no overlap, finite world positions',()=>{const bp=compileImageData(makePattern('glyph',128),{brickBudget:44}).blueprint;assert.equal(bp.grid.cols%2,0);assert.ok(bp.brickCount<=44);assert.equal(validateBlueprint(bp).ok,true);assert.equal(new Set(bp.targets.map(t=>t.targetId)).size,bp.targets.length);for(const t of bp.targets)assert.ok([t.worldXmm,t.worldYmm,t.worldZmm].every(Number.isFinite))});
test('transparent background remains empty',()=>{const image=makePattern('transparent',128),bp=compileImageData(image,{brickBudget:48}).blueprint;assert.ok(bp.brickCount<bp.grid.rows*bp.grid.cols/2);assert.ok(bp.targets.every(t=>t.coverage>=EMPTY_COVERAGE_THRESHOLD))});
test('contain preserves approximate aspect and cover is supported',()=>{const image=makePattern('diagonal',128);image.width=128;image.height=128;const contain=compileImageData(image,{brickBudget:36,fitMode:'contain'}).blueprint,cover=compileImageData(image,{brickBudget:36,fitMode:'cover'}).blueprint;assert.equal(contain.source.fitMode,'contain');assert.equal(cover.source.fitMode,'cover');assert.ok(contain.brickCount<=36&&cover.brickCount<=36)});
test('alpha-weighted colour ignores fully transparent RGB garbage',()=>{const img=blank(32,16);for(let y=0;y<16;y++)for(let x=0;x<32;x++){pixel(img,x,y,x<16?[214,48,54,255]:[0,0,255,0])}const bp=compileImageData(img,{brickBudget:8,boardLimits:{maxWidthMm:64,maxHeightMm:32}}).blueprint;assert.ok(bp.targets.length>0);assert.ok(bp.targets.every(t=>t.colour==='red'))});
test('source input limits reject absurd dimensions before work',()=>{const image={width:5000,height:1,data:new Uint8ClampedArray(5000*4)};assert.throws(()=>compileImageData(image),/image_too_large/)});
test('mixed palette edges do not invent a third source colour',()=>{const bp=compileImageData(makePattern('diagonal',128),{brickBudget:48}).blueprint;const colours=new Set(bp.targets.map(t=>t.colour));assert.deepEqual([...colours].sort(),['blue','red','white'])});

test('1024-pixel compiler cap prevents high-memory integral allocations', async () => {
  const image = { width: 1025, height: 1, data: new Uint8ClampedArray(1025 * 4) };
  assert.throws(() => compileImageData(image), /image_too_large/);
});
