import test from 'node:test'; import assert from 'node:assert/strict';
import { createRuntimeBridge } from '../../apps/web/src/webmcp/runtime-bridge.js'; import { createFixtureRuntime } from '../fixtures/logo-robo-runtime.js'; import { createObservationService } from '../../apps/web/src/perception/observation-service.js'; import { createCameraRig } from '../../apps/web/src/perception/camera-rig.js'; import { lookAt, mat4Multiply, perspective } from '../../apps/web/src/perception/math.js'; import { projectObjectBounds } from '../../apps/web/src/perception/projection.js'; import { visibilityForObject } from '../../apps/web/src/perception/visibility.js';
test('tray observation returns bounded pixel boxes and one consistent revision',async()=>{const r=createFixtureRuntime(),s=createObservationService({bridge:createRuntimeBridge(r)}),o=await s.observe({cameraId:'tray_camera',limit:50});assert.equal(o.ok,true);assert.equal(o.snapshotRevision,r.getWorldRevision());for(const d of o.detections){const [x0,y0,x1,y1]=d.bboxPx;assert.ok(x0>=0&&y0>=0&&x1<=o.widthPx&&y1<=o.heightPx&&x1>x0&&y1>y0);}});
test('camera resize changes pixel coordinate system without corrupt boxes',async()=>{const r=createFixtureRuntime(),rig=createCameraRig(),s=createObservationService({bridge:createRuntimeBridge(r),cameraRig:rig});const a=await s.observe({cameraId:'tray_camera'});rig.resize(960,540);const b=await s.observe({cameraId:'tray_camera'});assert.equal(b.widthPx,960);assert.equal(b.heightPx,540);assert.notDeepEqual(a.detections[0].bboxPx,b.detections[0].bboxPx);});
test('projection clips a near-edge box safely',()=>{const rig=createCameraRig(),camera=rig.getCamera('tray_camera',1),obj={id:'edge',type:'brick',position:{xMm:675,yMm:-180,zMm:22},bounds:{xMm:64,yMm:32,zMm:22},yawDeg:18};const p=projectObjectBounds(obj,camera);assert.ok(p);assert.ok(p.bboxPx.every(Number.isFinite));assert.ok(p.bboxPx[2]<=camera.widthPx);});
test('occlusion rejects a brick hidden behind another in top-down view',()=>{const rig=createCameraRig(),camera=rig.getCamera('tray_camera',1),front={id:'front',type:'brick',position:{xMm:430,yMm:-180,zMm:60},bounds:{xMm:80,yMm:50,zMm:30}},back={id:'back',type:'brick',position:{xMm:430,yMm:-180,zMm:20},bounds:{xMm:64,yMm:32,zMm:22}};const v=visibilityForObject(back,[front,back],camera);assert.equal(v.visible,false);});
test('old observation remains immutable after world change',async()=>{const r=createFixtureRuntime(),s=createObservationService({bridge:createRuntimeBridge(r)}),a=await s.observe({cameraId:'tray_camera'});const x=a.detections[0].worldXmm;r.fixture.moveBrick(a.detections[0].objectId,{xMm:x+100});assert.equal(a.detections[0].worldXmm,x);const b=await s.observe({cameraId:'tray_camera'});assert.notEqual(b.snapshotRevision,a.snapshotRevision);});

test('rotated perspective camera projection remains finite',()=>{const view=lookAt([720,-520,620],[400,-180,20],[0,0,1]),projection=perspective(48,16/9,10,2000),camera={widthPx:640,heightPx:360,position:[720,-520,620],viewProjectionMatrix:mat4Multiply(projection,view)};const p=projectObjectBounds({id:'rot',position:{xMm:400,yMm:-180,zMm:24},bounds:{xMm:64,yMm:32,zMm:22},yawDeg:31},camera);assert.ok(p);assert.ok(p.bboxPx.every(Number.isFinite));});
