import test from 'node:test'; import assert from 'node:assert/strict';
import { createRuntimeBridge } from '../../apps/web/src/webmcp/runtime-bridge.js'; import { createLogoRoboToolHandlers } from '../../apps/web/src/webmcp/tool-handlers.js'; import { createFixtureRuntime } from '../fixtures/logo-robo-runtime.js';
function harness(){const runtime=createFixtureRuntime();return{runtime,h:createLogoRoboToolHandlers({bridge:createRuntimeBridge(runtime)})};}
async function placeOne(h,targetId='t_001') {const state=await h.getBuildState({status:'unfilled',colour:'white',limit:10});const target=state.targets.find(t=>t.id===targetId)??state.targets[0];assert.ok(target);assert.equal((await h.claimTarget({targetId:target.id})).ok,true);const obs=await h.observeCamera({cameraId:'tray_camera',colour:'white',type:'brick',limit:20});const b=obs.detections[0];assert.ok(b);assert.equal((await h.moveTool({xMm:b.worldXmm,yMm:b.worldYmm,zMm:b.worldZmm+100,speedMmS:500})).ok,true);assert.equal((await h.moveTool({xMm:b.worldXmm,yMm:b.worldYmm,zMm:b.worldZmm,speedMmS:220})).ok,true);assert.equal((await h.latch()).ok,true);assert.equal((await h.moveTool({xMm:b.worldXmm,yMm:b.worldYmm,zMm:b.worldZmm+140,speedMmS:500})).ok,true);await h.observeCamera({cameraId:'canvas_camera',type:'target',limit:20});assert.equal((await h.moveTool({xMm:target.position.xMm,yMm:target.position.yMm,zMm:target.position.zMm+120,speedMmS:500})).ok,true);assert.equal((await h.moveTool({xMm:target.position.xMm,yMm:target.position.yMm,zMm:target.position.zMm,speedMmS:180})).ok,true);const release=await h.unlatch();assert.equal(release.ok,true);assert.equal(release.targetSnap.targetId,target.id);const final=await h.getBuildState({limit:20});assert.equal(final.targets.find(t=>t.id===target.id).status,'filled');return true;}
test('one complete primitive brick loop fills the target',async()=>{const {h}=harness();await placeOne(h);});
test('human interference causes stale_state then observe/recover with another brick',async()=>{const {runtime,h}=harness();const o=await h.observeCamera({cameraId:'tray_camera',colour:'white',type:'brick'}),a=o.detections[0];runtime.fixture.takeBrick(a.objectId);const stale=await h.moveTool({xMm:a.worldXmm,yMm:a.worldYmm,zMm:a.worldZmm,speedMmS:200});assert.equal(stale.reason,'stale_state');const fresh=await h.observeCamera({cameraId:'tray_camera',colour:'white',type:'brick'});assert.ok(fresh.detections.every(d=>d.objectId!==a.objectId));});
test('target occupied during transfer is visible on recheck',async()=>{const {runtime,h}=harness();assert.equal((await h.claimTarget({targetId:'t_001'})).ok,true);runtime.fixture.fillTarget('t_001');const s=await h.getBuildState({limit:20});assert.equal(s.targets.find(t=>t.id==='t_001').status,'filled');assert.ok(s.targets.some(t=>t.id==='t_002'&&t.status==='unfilled'));});
test('failed latch returns stable recovery error',async()=>{const {h}=harness();const r=await h.latch();assert.equal(r.ok,false);assert.equal(r.reason,'no_brick_in_capture');assert.equal(h.activity.list()[0].state,'RECOVER');});
test('collision preserves fixture final requested pose and permits safer recovery',async()=>{const {runtime,h}=harness(),before=runtime.robot.getState().tcp;const bad=await h.moveTool({xMm:90,yMm:120,zMm:60,speedMmS:200});assert.equal(bad.reason,'collision');assert.deepEqual(runtime.robot.getState().tcp,before);const good=await h.moveTool({xMm:90,yMm:20,zMm:160,speedMmS:200});assert.equal(good.ok,true);});
test('fixture agent loop reliability is 50/50',async()=>{let passed=0;for(let i=0;i<50;i+=1){const {h}=harness();try{await placeOne(h);passed+=1;}catch{}}assert.equal(passed,50);});
