import test from 'node:test'; import assert from 'node:assert/strict';
import { registerWebMcpTools, getLogoRoboToolDefinitions } from '../../apps/web/src/webmcp/register-oracle3-tools.js';
import { createRuntimeBridge } from '../../apps/web/src/webmcp/runtime-bridge.js';
import { createLogoRoboToolHandlers } from '../../apps/web/src/webmcp/tool-handlers.js';
import { createFixtureRuntime } from '../fixtures/logo-robo-runtime.js';

test('registers exactly the bounded six-tool LOGO ROBO surface',async()=>{const registered=[],life=[];globalThis.document={modelContext:{async registerTool(tool,options){registered.push({tool,options});}}};const runtime=createFixtureRuntime();const result=await registerWebMcpTools(runtime,e=>life.push(e));assert.equal(result.ok,true);assert.equal(result.toolCount,6);assert.deepEqual(result.toolNames,['get_build_state','observe_camera','move_tool','latch','unlatch','claim_target']);assert.equal(registered.length,6);for(const {tool,options} of registered){assert.ok(tool.name.length<=30);assert.ok(tool.description.length<=500);assert.equal(tool.inputSchema.type,'object');assert.equal(typeof tool.execute,'function');assert.equal(typeof tool.annotations.readOnlyHint,'boolean');assert.ok(options.signal instanceof AbortSignal);}const obs=registered.find(x=>x.tool.name==='observe_camera').tool;const output=JSON.parse(await obs.execute({cameraId:'tray_camera',colour:'white',limit:10}));assert.equal(output.ok,true);assert.ok(output.detections.length>=1);assert.equal(life.filter(e=>e.status==='discovered').length,6);});
test('progressive enhancement has no exception without native WebMCP',async()=>{globalThis.document={};const r=await registerWebMcpTools(createFixtureRuntime());assert.equal(r.ok,false);assert.match(r.reason,/modelContext/);});
test('production-unavailable handlers return stable runtime_unavailable',async()=>{const handlers=createLogoRoboToolHandlers({bridge:createRuntimeBridge(null)});const r=await handlers.getBuildState({limit:5});assert.equal(r.ok,false);assert.equal(r.reason,'runtime_unavailable');});
test('schemas forbid high-level manipulation shortcuts and bound inputs',()=>{const defs=getLogoRoboToolDefinitions(createLogoRoboToolHandlers({bridge:createRuntimeBridge(createFixtureRuntime())}));const names=defs.map(d=>d.name);for(const forbidden of ['place_brick','pick_brick','build_logo','execute_build_plan','set_joints','move_joint'])assert.equal(names.includes(forbidden),false);const move=defs.find(d=>d.name==='move_tool');assert.equal(move.inputSchema.additionalProperties,false);assert.equal(move.inputSchema.properties.speedMmS.maximum,3000);});
